function [y_out] = Trmvp_ln_unb_var2(L, x, y)
% TRMVP_LN_UNB_VAR2
% TRMVP_LN_UNB_VAR2 = [TR]iangular [M]atrix-[V]ector multiply [P]lus y, 
% with [L]ower triangular matrix that is [N]ot trans-posed, [UNB]locked 
% [VAR]iant [2].

% This method calculates a matrix-vector multiplication y_out = Ax + y with
% efficiency gain by assuming A is an lower triangular matrix (A->L is a
% lower triangular matrix).

% The matrix L is sliced by rows and columns into sub-matrices
% and vectors prior to calculating the vector-alpha scalar of L_slice * chi1.

% NOTE: The following code was created using the SPARK code generator.
% http://edx-org-utaustinx.s3.amazonaws.com/UT501x/Spark/index.html

% NOTE: You can review a visualization of this algorithm by copying the
% code to this applicaiton.
% http://edx-org-utaustinx.s3.amazonaws.com/UT501x/PictureFLAME/PictureFLAME.html

% UT Austin Linear Algebra: Foundations to Frontiers (http://www.ulaff.net)
% LAFF Homework 4.3.2.3
% Date: 11/28/2020
% Created by: Logan Kells

  [ LTL, LTR, ...
    LBL, LBR ] = FLA_Part_2x2( L, ...
                               0, 0, 'FLA_TL' );

  [ xT, ...
    xB ] = FLA_Part_2x1( x, ...
                         0, 'FLA_TOP' );

  [ yT, ...
    yB ] = FLA_Part_2x1( y, ...
                         0, 'FLA_TOP' );

  while ( size( LTL, 1 ) < size( L, 1 ) )

    [ L00,  l01,      L02,  ...
      l10t, lambda11, l12t, ...
      L20,  l21,      L22 ] = FLA_Repart_2x2_to_3x3( LTL, LTR, ...
                                                     LBL, LBR, ...
                                                     1, 1, 'FLA_BR' );

    [ x0, ...
      chi1, ...
      x2 ] = FLA_Repart_2x1_to_3x1( xT, ...
                                    xB, ...
                                    1, 'FLA_BOTTOM' );

    [ y0, ...
      psi1, ...
      y2 ] = FLA_Repart_2x1_to_3x1( yT, ...
                                    yB, ...
                                    1, 'FLA_BOTTOM' );
    %------------------------------------------------------------%
    % Calculate alpha*x + y operations; where alpha=chi1.
    
    % Commented out the next operation because l01 is assumed to be zeros
    % vector based on L being a lower triangular matrix.
    % y0 = laff_scal(chi1, u01) + y0;
    
    psi1 = laff_scal(chi1, lambda11) + psi1;
    y2 = laff_scal(chi1, l21) + y2;
    %------------------------------------------------------------%

    [ LTL, LTR, ...
      LBL, LBR ] = FLA_Cont_with_3x3_to_2x2( L00,  l01,      L02,  ...
                                             l10t, lambda11, l12t, ...
                                             L20,  l21,      L22, ...
                                             'FLA_TL' );

    [ xT, ...
      xB ] = FLA_Cont_with_3x1_to_2x1( x0, ...
                                       chi1, ...
                                       x2, ...
                                       'FLA_TOP' );

    [ yT, ...
      yB ] = FLA_Cont_with_3x1_to_2x1( y0, ...
                                       psi1, ...
                                       y2, ...
                                       'FLA_TOP' );
  end
  y_out = [ yT
            yB ];
return

